### ISSUE TITLE
Platform linux not supported

### ISSUE THREAD

**Issue by doofin** [neandertech/dexsearch#2]
Hi,I got this error `java.lang.RuntimeException: Platform linux not supported, PRs are welcome`
![image](https://user-images.githubusercontent.com/6041353/211168015-859132c7-3760-4e8a-ba0c-a4bdfffc2561.png)

**Comment by Baccata** [comment]
Hi. Are you interested in contributing a fix ?

**Comment by Baccata** [comment]
Fixed and released  (0.1.5)

**Comment by doofin** [comment]
Thanks!
